apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-detoiserver-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-detoiserverpayment-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi